name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - masters 
jobs:
  build:
    # Job name is Greeting
    name: Build and deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.5.7
